#!/usr/bin/env bash

set -xe

#
# Taken from example 5c of afni_proc.py ("RETROICOR example c (modern): censoring and bandpass filtering")
#
# Run like: REDO=1 SUBJECT=10845 VISIT=20100924 ~/src/restPreproc/rest_preproc_afniproc_torque
#
#2013-08-06 -- add "run like", changes to Dimon in makerestimage.bash
#2013-07-16 -- intial
#

[ -z "$SUBJECT" -o -z "$VISIT" ] && echo "need SUBJECT and VISIT; e.g.    qsub $0 -v SUBJECT=10845,VISIT=20100924"  && exit 1

[ -z "$VERSION" ] && VERSION="afniproc"

echo "$SUBJECT $VISIT: $VERSION"

scriptdir=$(cd $(dirname $0);pwd)              
[[ $scriptdir =~ spool ]] && scriptdir="/home/foranw/src/restPreproc"
which afni_proc.py
# define origepi, physioDir, FSDir,dicomRootDir, subjRootDir, physiofile
source $scriptdir/rewardrest.cfg 


# check for origepi ("rest.nii.gz"), or make it 
source $scriptdir/makerestimage.bash

savedir=$(dirname $origepi)/$VERSION

[ -z "$physiofile" -o ! -r "$physiofile" ] && echo "NO PHYSIO! in $physioDir/$SUBJECT/$VISIT/" && exit 1

[ -n "$REDO" -a -r $savedir ] && rm -r $savedir
[ -r "$savedir" ] && echo "$savedir already exists!\nuse: REDO=1 $0 $@ " && exit 1
mkdir $savedir

cd $savedir 
# censor motion changed (.2 default) to avoid:
#   FATAL ERROR: 3dDeconvolve dies: Insufficient data
# bandpass changed (.01 0.1 default) to match aarthi's 
# blur (fwhm default 6) cahnged to match aarthi's
# change tlrc_base to avg152 -- hopefully match
#    /data/Luna1/ni_tools/standard_templates/mni_icbm152_nlin_asym_09c/mni_icbm152_t1_tal_nlin_asym_09c_2mm.nii
afni_proc.py \
      -subj_id $s                             \
      -dsets $origepi                         \
      -copy_anat ../anat/mprage_bet.nii.gz    \
      -tlrc_base MNI_avg152T1+tlrc            \
      -blocks despike ricor tshift align tlrc \
              volreg blur mask regress        \
      -tcat_remove_first_trs 3                \
      -ricor_regs_nfirst 3                    \
      -ricor_regs $physiofile                 \
      -volreg_align_e2a                       \
      -volreg_tlrc_warp                       \
      -blur_size 5                            \
      -regress_motion_per_run                 \
      -regress_censor_motion 0.4              \
      -regress_bandpass 0.009 0.08            \
      -regress_apply_mot_types demean deriv   \
      -regress_run_clustsim no                \
      -regress_est_blur_errts

tcsh -xef proc.$s | tee output.proc.$s

# link errts as rest_mni.nii.gz
3dcopy *results/errts*HEAD rest_preproc_mni.nii.gz 
